services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    command: celery -A make_celery worker --loglevel=info
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379